# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NThkMTU3YTNiN2U0MjQ5NjA5NGI3N2ZlMzIwNWMwNTk4MTI4NDVhODQ4ZDBiNDNlMzZiOGEyMDBjYmVjMjVkMjVmYjI5Yzc4ZTg5YWEzODY4MzExODFhODc4M2IxMjVmNDQ2NWYyNjk4MTk2YjVmYzQwN2NhMTVkNGM4ZTUyY2U=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
